### ISSUE TITLE
Stuk

### ISSUE THREAD

**Issue by WillemJan** [zevv/lsofgraph#1]
lsof -n -F | ./lsofgraph | dot -Tjpg > /tmp/lsof.jpg

Then you wait untill you an ons weight, but nothing heppens.

root@kbresearch:/opt/home/wfa010/lsofgraph# file /tmp/lsof.jpg
/tmp/lsof.jpg: JPEG image data, JFIF standard 1.01, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), default quality"
root@kbresearch:/opt/home/wfa010/lsofgraph# ls -lah /tmp/lsof.jpg
-rw-rw-r-- 1 wfa010 wfa010 738 Feb  8 17:32 /tmp/lsof.jpg

**Comment by zevv** [comment]
Fixed
- On 2016-02-08 20:30:28 +0100, WillemJan Faber wrote:

> lsof -n -F | ./lsofgraph | dot -Tjpg > /tmp/lsof.jpg
> 
> Then you wait untill you an ons weight, but nothing heppens.
> 
> root@kbresearch:/opt/home/wfa010/lsofgraph# file /tmp/lsof.jpg
> /tmp/lsof.jpg: JPEG image data, JFIF standard 1.01, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), default quality"
> root@kbresearch:/opt/home/wfa010/lsofgraph# ls -lah /tmp/lsof.jpg
> -rw-rw-r-- 1 wfa010 wfa010 738 Feb  8 17:32 /tmp/lsof.jpg
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/lsofgraph/issues/1

## 

:wq
^X^Cy^K^X^C^C^C^C
