### ISSUE TITLE
lua: ./lsofgraph:54: unexpected symbol near `...'

### ISSUE THREAD

**Issue by xaionaro** [zevv/lsofgraph#11]
```
# lsof -n -F |./lsofgraph | dot -Tjpg > /tmp/a.jpg
lua: ./lsofgraph:54: unexpected symbol near `...'
```

**Comment by zevv** [comment]
What Lua version are you using?

Quoting Okunev Yu Dmitry (2018-06-10 10:27:36)
> ```
> # lsof -n -F |./lsofgraph | dot -Tjpg > /tmp/a.jpg
> lua: ./lsofgraph:54: unexpected symbol near `...'
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/lsofgraph/issues/11


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by xaionaro** [comment]
```
$ lua -v
Lua 5.0.3  Copyright (C) 1994-2006 Tecgraf, PUC-Rio
```

**Comment by zevv** [comment]
There's your problem I guess, I have only tested Lua 5.2 and up. I will
see if I can make the script compatible with Lua 5.0, for now pleasetry
a newer Lua  version or check out the Python or Perl port of lsofgraph.


Quoting Okunev Yu Dmitry (2018-06-10 11:27:34)
> ```
> $ lua -v
> Lua 5.0.3  Copyright (C) 1994-2006 Tecgraf, PUC-Rio
> ```
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/lsofgraph/issues/11#issuecomment-396034448


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by xaionaro** [comment]
Ok, thanks.
