### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by dmullis** [zevv/lsofgraph#2]
$ sudo lsof -n -F | ./lsofgraph

$ lsof -v
lsof version information:
    revision: 4.89
    ...

$ uname --kernel-release --kernel-version --operating-system 
4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 GNU/Linux

**Comment by zevv** [comment]
Can you send the raw output of `lsof -n -F` on your machine, and the output of `lua -v`

**Comment by dmullis** [comment]
Past the "no output" issue, but seeing another failure.

$ sudo lsof -n -F | ./lsofgraph
/usr/bin/lua: ./lsofgraph:54: unexpected symbol near `...'
 ...

$ lua -v
Lua 5.0.3  Copyright (C) 1994-2006 Tecgraf, PUC-Rio

Output of `lsof -n -F` is large.  Last record of it is below, let me know if you need more.

s4096
i2
k26
n/
ftxt
a 
l 
tunknown
n/proc/20938/exe

**Comment by zevv** [comment]
Yeah, that one is pretty simple: your Lua version is too old (Lua 5.0.3 was released in 2003, some years ago :) ).

Please try again with Lua 5.1 or newer
