### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by unphased** [zevv/lsofgraph#5]
```
~/D/lsofgraph ❯❯❯ sudo lsof | ./lsofgraph
digraph G {
        rankdir = LR;
        node [ shape=box, style="rounded,filled" width=0, height=0, fontname=Helvetica, fontsize=10];
        edge [ fontname=Helvetica, fontsize=10];
lua: ./lsofgraph:54: bad argument #2 to 'format' (number expected, got string)
stack traceback:
        [C]: in function 'format'
        ./lsofgraph:54: in function 'printf'
        ./lsofgraph:169: in main chunk
        [C]: in ?

```
similar output when using `-n -F` etc. (hacker news brought me here)

**Comment by clemtaylor** [comment]
Same thing:
```
lsof -n -f | ./lsofgraph | dot -Tjpg | display -
/usr/bin/lua: ./lsofgraph:54: bad argument #2 to 'format' (number expected, got string)
stack traceback:
	[C]: in function 'string.format'
	./lsofgraph:54: in local 'printf'
	./lsofgraph:169: in main chunk
	[C]: in ?
Error: <stdin>: syntax error in line 5
```

**Comment by zevv** [comment]
Probably lazy parsing of the output. Can you send me the raw output of `lsof -n -F` and `lua -v`

**Comment by loginoff** [comment]
I had the same error when doing
`lsof | ./lsofgraph`
But doing
`lsof -n -F | ./lsofgraph` works just fine.
So I think they are just using the wrong flags for `lsof`.

**Comment by daemianmack** [comment]
Neither `lsof` command referenced in this issue seems to work for me on master as of SHA 0801ea080962.

OSX version 10.13.3 (17D47)
Lua version 5.2.4
lsof version 4.89

As documented in README...

```
> sudo lsof -n -F | ./lsofgraph
lua: ./lsofgraph:125: table index is nil
stack traceback:
        ./lsofgraph:125: in function 'find_conns'
        ./lsofgraph:154: in main chunk
        [C]: in ?
```

Nor does `lsof` without flags seem to work...

```
> sudo lsof | ./lsofgraph
digraph G {
        rankdir = LR;
        node [ shape=box, style="rounded,filled" width=0, height=0, fontname=Helvetica, fontsize=10];
        edge [ fontname=Helvetica, fontsize=10];
lua: ./lsofgraph:54: bad argument #2 to 'format' (number expected, got string)
stack traceback:
        [C]: in function 'format'
        ./lsofgraph:54: in function 'printf'
        ./lsofgraph:169: in main chunk
        [C]: in ?
```

Happy to help troubleshoot further. 

Cool project, by the way, looking forward to playing with it!

**Comment by zevv** [comment]
Same question to you: could you send me the output of `lsof -n -F` of your machine?

**Comment by daemianmack** [comment]
Sure. I've emailed the 1.5Mb listing to the email address I found in this project's git history.

**Comment by zevv** [comment]
Thanks, received in good order. It seems that the Mac OS output has some differences from linux, and some naive assumptions in the script broke.

I'll see if there is more I can do to properly parse MacOS output.

**Comment by zevv** [comment]
Please retry with 361075a

**Comment by daemianmack** [comment]
SHA 361075a2584 works for me. Thanks!

**Comment by zevv** [comment]
Ok, closing for now. Let me know if anything else breaks.

**Comment by unphased** [comment]
Works now! Perhaps you could also document that you must use `-F` flag for this to work. 

This tool is really cool.

**Comment by zevv** [comment]
Check was added.
