### ISSUE TITLE
Add link to python version

### ISSUE THREAD

**Issue by akme** [zevv/lsofgraph#9]
Hey, nice job with script, i made python version of it, could you add link to [lsofgraph-python](https://github.com/akme/lsofgraph-python)?

**Comment by gvalkov** [comment]
For what it's worth, I made another Python port of your script. It's not yet as complete as @akme's, but I think it's written in a more idiomatic way.

https://github.com/gvalkov/python-lsofgraph/blob/master/lsofgraph.py
